development:
  adapter: postgresql
  database: louerunsenior
  host:  localhost
  pool: 5
  timeout: 5000
  username: geeksters
  password: geeksters

test:
  adapter: postgresql
  database: louerunsenior_test
  # database: louerunsenior_test<%= ENV['TEST_ENV_NUMBER'] %>
  host:  localhost
  pool: 5
  timeout: 5000
  username: geeksters
  password: geeksters

production:
  adapter: postgresql
  database: louerunsenior
  host:  localhost
  pool: 5
  timeout: 5000
  username: geeksters
  password: geeksters
